# Generated by Django 5.0.8 on 2024-08-13 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_ai', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='memeya',
        ),
    ]
